// Utility for accessing schema-defined field names used across the frontend.
// The schema is generated by the backend (see python_backend/schemas.py)
// and copied to /data/grade_schema.json. This module exposes the fields and
// a helper to lazily fetch the full schema if needed.

/**
 * Keys used by the grading schema. These correspond to fields returned by the
 * backend when grading submissions.
 */
export const FIELDS = {
  STUDENT: 'student',
  STUDENT_NAME: 'student_name',
  ANSWER: 'answer',
  SCORE: 'score',
  TOTAL_SCORE: 'total_score',
  MAX_SCORE: 'max_score',
  FEEDBACK: 'feedback',
  BREAKDOWN: 'breakdown',
  CRITERION: 'criterion',
  POINTS_AWARDED: 'points_awarded',
  MAX_POINTS: 'max_points'
};

let cachedSchema = null;

/**
 * Load the grade schema from `/data/grade_schema.json` if available.
 *
 * @returns {Promise<Object|null>} Parsed schema object or `null` on failure.
 */
export async function loadGradeSchema() {
  if (cachedSchema) return cachedSchema;
  try {
    const resp = await fetch('/data/grade_schema.json');
    if (!resp.ok) throw new Error('Schema not found');
    cachedSchema = await resp.json();
  } catch (err) {
    console.warn('Unable to load grade_schema.json:', err);
    cachedSchema = null;
  }
  return cachedSchema;
}
